### ISSUE TITLE
Lỗi lấy danh sách lớp

### ISSUE THREAD

**Issue by MinhCao031** [duong755/schedule-uet-fe#2]
Một số môn học bằng tiếng Anh (INT2208E, INT3401E, ...) không lấy được danh sách lớp.
Theo mình do regular expression còn thiếu trường hợp, mong ad bổ sung ạ <3

**Comment by duong-ngo** [comment]
Đúng là mình dùng regex để kiểm tra đoạn đó và sót mất các lớp học bằng tiếng Anh thật.
Mình đã sửa lại rồi nhé.

Cảm ơn bạn vì issue đầu tiên :relaxed: :heart:
